class_name ASP

enum {
	MODE_PLAYBACK_DO_LOOP = 0,
	MODE_PLAYBACK_NO_LOOP = 1,
	MODE_SFX_NONE = 10,
	MODE_SFX_FADE = 11,
	MODE_INSERT_POS_AT_NUMERATOR = 20,
	MODE_INSERT_POS_AT_DENOMINATOR = 21,
	MODE_INSERT_POS_AT_MEASURE = 22,
}



